field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  60cf895a-c218-4266-b92e-84e7c9af2baa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 484ad434-775d-49da-ba41-8fef629fdf05 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fcbda06-ad69-4051-a078-f4a920cf1278
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e26bccc0-5f6e-465a-bc53-ca518d9a70d8 # Articles
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63af6627-7664-4bc0-b5aa-e1d844a3ce63
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d2bff817-c170-4c81-81c8-715894d6795d # Articles Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f557a29c-6091-4b0c-8b0f-d4981f540255
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1a4c4f22-b6ec-4dc8-8b67-ef9d928180d0 # Topic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4160bb5-4a29-4c3d-80f9-0ea47ba4d264
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8b780bbf-5c14-4590-9eac-dda4a4fb6dcd # Restrict to topic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d71b9389-8b08-492e-85bd-57a507bacb5e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 073bb589-e25f-4852-95c5-3aa6126e13b0 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f953c711-65b4-49d4-96f5-7ca9659cb813
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b8473c9e-0759-45e7-bc02-b5e00a31c275 # Style
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a262dd36-647b-479e-a2a2-5d9c06805f0a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 42c099ce-f401-404a-9884-34b24e55168a # Add top border
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c568a4-b3c8-41e1-a329-bc2a7136ab78
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 14b97a17-1192-45ff-a041-b14cc2b7fdcd # Show Author and Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6560461-08f6-4f97-a101-23d7741e1c85
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 41660015-9759-4d64-8e07-842c7b9bd715
        userCondition: null
fields:
  1a4c4f22-b6ec-4dc8-8b67-ef9d928180d0: # Topic
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topic
    instructions: 'Add link to topic'
    name: Topic
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:a3a00a5e-73ba-4e8a-9800-375c9be802a9' # Topic
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8b780bbf-5c14-4590-9eac-dda4a4fb6dcd: # Restrict to topic
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: restrictToTopic
    instructions: 'Only show newest articles from selected topic'
    name: 'Restrict to topic'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  14b97a17-1192-45ff-a041-b14cc2b7fdcd: # Show Author and Date
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showAuthorAndDate
    instructions: null
    name: 'Show Author and Date'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  42c099ce-f401-404a-9884-34b24e55168a: # Add top border
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: addTopBorder
    instructions: null
    name: 'Add top border'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  073bb589-e25f-4852-95c5-3aa6126e13b0: # Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      addDefaultOptions: true
      addMobileOptions: false
      defaultWidth: default
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\WidthField
  484ad434-775d-49da-ba41-8fef629fdf05: # Heading
    columnSuffix: null
    contentColumnType: string(240)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  b8473c9e-0759-45e7-bc02-b5e00a31c275: # Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Featured
            -
              - value
              - featured
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Boxed
            -
              - value
              - boxed
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Cards
            -
              - value
              - cards
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  d2bff817-c170-4c81-81c8-715894d6795d: # Articles Limit
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: articlesLimit
    instructions: 'How many new articles to show if no articles are selected'
    name: 'Articles Limit'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 1
      max: null
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  e26bccc0-5f6e-465a-bc53-ca518d9a70d8: # Articles
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: articles
    instructions: 'Leave blank to show the newest articles.'
    name: Articles
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Add article'
      showSiteMenu: false
      source: null
      sources:
        - 'section:6087074e-26c7-4216-b6b3-86fbe41e437f' # Article
        - 'section:a6676538-ee52-4938-aaff-8d9d46b669af' # Page
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: articles
name: Articles
sortOrder: 10
