field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  0ce9bef7-d2ea-4e7e-8ead-86e6d8771e8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 051d92e2-649b-4487-b9de-31b3c4bb7d86 # Audio File
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdf09014-ae48-4714-abf3-c5ce252cf772
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60d7202b-beaa-4319-83f3-33bcef815c6d # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5658879-1a7f-4544-951b-0e6870544450
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6af65f26-da0b-4cb2-aacc-97fdfe143f83
        userCondition: null
fields:
  051d92e2-649b-4487-b9de-31b3c4bb7d86: # Audio File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audioFile
    instructions: 'Unterstützte Formate: mp3, ogg, wav. Der Upload einer umfangreichen Audio-Datei benötigt etwas Zeit. Bitte Geduld, bis der Spinner rechts oben im Upload-Fenster verschwindet.'
    name: 'Audio File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: audio
      localizeRelations: true
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  60d7202b-beaa-4319-83f3-33bcef815c6d: # Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Styled
            -
              - value
              - styled
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: audio
name: Audio
sortOrder: 7
