field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  10dce2c2-885b-4a43-b29b-bd3e0ad3c037:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf0f9db1-27b9-4a19-8e36-fc5439109d73 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd27d15-a17e-44f7-a1fa-32fa25901188
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6f9a628-cf74-47fd-aebe-0587bea06e3c # Columns
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28e722c2-adec-43b6-b715-9d3636c48a65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9e12f8a-d90b-4458-a578-7025f7d0d90a # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 334032fb-461b-4b94-816f-6fd1d72a1820
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7e7c06a8-5d97-4fc6-b2cb-5dd34caec986 # Margins Y
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a8adb43-29d4-49a7-8f92-5e57000250b1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ea0da518-95b9-47c2-8dec-9f2ff43ca7f4 # Background color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd829ced-e110-4426-8c88-cdd179191ccb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 06cc6bfc-a991-4aa6-99af-018de34f8bf4 # Text color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17ff364c-6297-4467-878e-a34056c71427
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: fa8cc2ba-1458-4ec3-a18a-c0be9a0f032b
        userCondition: null
fields:
  06cc6bfc-a991-4aa6-99af-018de34f8bf4: # Text color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: foregroundColor
    instructions: null
    name: 'Text color'
    searchable: false
    settings:
      defaultColor: default
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\ThemeColorField
  7e7c06a8-5d97-4fc6-b2cb-5dd34caec986: # Margins Y
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: marginsY
    instructions: null
    name: 'Margins Y'
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\MarginsYField
  a6f9a628-cf74-47fd-aebe-0587bea06e3c: # Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: columns
    instructions: null
    name: Columns
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 285376694
      columns:
        __assoc__:
          -
            - 57dba12d-3dba-4e01-a8e5-7ed1323f9c68 # Span
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 20f9b230-8862-4058-9cf3-7c7a78e44a13 # Column
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_22_columns}}'
      fieldLayout: row
      maxRows: 3
      minRows: 2
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a column'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  b9e12f8a-d90b-4458-a578-7025f7d0d90a: # Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      addDefaultOptions: false
      addMobileOptions: false
      defaultWidth: xl
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\WidthField
  bf0f9db1-27b9-4a19-8e36-fc5439109d73: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  ea0da518-95b9-47c2-8dec-9f2ff43ca7f4: # Background color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background color'
    searchable: false
    settings:
      defaultColor: default
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\ThemeColorField
handle: columns
name: 'Multi Columns'
sortOrder: 17
