field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  ca61ad5a-0964-41ed-9999-68adb77f2c4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 118622b7-20ad-4b1d-8d78-5d49bbdbcd68 # Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5a8ee72-23ed-4eb3-b8f8-f50b9fd0f8fb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 2cf2c737-33d2-4b15-8933-7053b22d0020 # Parameter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b4acda6-3c79-470a-9c25-3c365c9af769
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 4808b0bb-4522-40f2-99db-1d1952569abc
        userCondition: null
fields:
  2cf2c737-33d2-4b15-8933-7053b22d0020: # Parameter
    columnSuffix: null
    contentColumnType: string(256)
    fieldGroup: null
    handle: parameter
    instructions: "Json-Format\r\n{\"section\":\"article\",\"limit\":3}"
    name: Parameter
    searchable: false
    settings:
      byteLimit: 256
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  118622b7-20ad-4b1d-8d78-5d49bbdbcd68: # Template
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: template
    instructions: null
    name: Template
    searchable: false
    settings:
      includeDirectory: _partials/dynamic
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\IncludeField
handle: dynamicBlock
name: 'Dynamic Block'
sortOrder: 16
