field: 20f9b230-8862-4058-9cf3-7c7a78e44a13 # Column
fieldLayouts:
  26e4ec57-da95-4152-8ba9-7260b26f3ea0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f305dd2-4b5a-4e51-b551-a0929fe4277f # Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d715d9d1-0dd7-4a5b-80ea-2bc45a291c70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 372fe1de-1ff1-4cb4-93fa-e51764a2dcc3 # Parameter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08f5a238-5cef-4568-8a4a-3836e335864c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed9bfbe2-79be-4568-b5e3-072384ba6b26
        userCondition: null
fields:
  7f305dd2-4b5a-4e51-b551-a0929fe4277f: # Template
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: template
    instructions: null
    name: Template
    searchable: false
    settings:
      includeDirectory: _partials/dynamic
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\IncludeField
  372fe1de-1ff1-4cb4-93fa-e51764a2dcc3: # Parameter
    columnSuffix: null
    contentColumnType: string(256)
    fieldGroup: null
    handle: parameter
    instructions: "Json-Format\r\n{\"section\":\"blog\",\"limit\":10}"
    name: Parameter
    searchable: false
    settings:
      byteLimit: 256
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: dynamicBlock
name: 'Dynamic Block'
sortOrder: 4
