field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  944975d0-4058-43ea-85dd-7342540932e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6c68905c-e96f-42e0-bc08-1f1f9d58d19f # __blank__
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58a276c0-52ce-4683-8327-5d9e9d5f91a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ce6b149-47e0-4fc8-8af6-697e642c5c43
        userCondition: null
fields:
  6c68905c-e96f-42e0-bc08-1f1f9d58d19f: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: null
    name: __blank__
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:49ccb4b8-c82b-4daf-9af9-1af874ad6dd4' # Embeds
      defaultUploadLocationSubpath: embeds
      localizeRelations: true
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: '{owner.site.handle}'
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select embed'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:49ccb4b8-c82b-4daf-9af9-1af874ad6dd4' # Embeds
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: embed
name: Embed
sortOrder: 6
