field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  ed608b4f-1636-46c5-8d82-71c445926709:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 512edbee-e5b1-4422-9597-eeffd72ee9e5 # __blank__
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 260ff83c-f05c-4f68-8bd0-b71637be1542
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5cc78695-cf9e-4492-af63-2f65b4b8c1aa # Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fd789d8-3938-4ad8-bce5-917e7634adb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa9610c7-3164-40fc-b309-0d4fe176344f
        userCondition: null
fields:
  5cc78695-cf9e-4492-af63-2f65b4b8c1aa: # Display
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: display
    instructions: null
    name: Display
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Accordion
            -
              - value
              - accordion
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  512edbee-e5b1-4422-9597-eeffd72ee9e5: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: __blank__
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1461995659
      columns:
        __assoc__:
          -
            - e35ec4e7-302c-49f6-b5ae-a95120fbd4c0 # Question
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 8fb04690-63b2-4e65-bb13-def05a978110 # Answer
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_23_items}}'
      fieldLayout: row
      maxRows: null
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add question/answer'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: faq
name: FAQ
sortOrder: 14
