field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  6dc16733-2a61-4e79-87af-07eb7503edc7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 143a7175-1ed7-4136-b81b-c00f6c0bb928 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 279e7d29-930a-4492-a5f7-d2e95a85dc42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 622de389-71f8-4b9f-ba40-260461f3bb7b # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3336bcb-2fde-4042-8de8-80213518ebf7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d9da022d-74c8-40d1-bd79-f3a6f208e542 # Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac426919-fdcd-44ba-b944-bd5d653db333
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3580d155-238d-43a1-b359-9c0634e988ed # Number of Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5c6d7ac-7d00-4422-b3b1-f18143e27a38
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8625d595-25d0-480e-88cd-cb7c5e9651bd # Aspect Ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0357ce54-9de8-46c0-bc6b-c647f7b06a18
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 269bf763-a69d-4e45-a7df-f4f1a7e0a2a1
        userCondition: null
fields:
  143a7175-1ed7-4136-b81b-c00f6c0bb928: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add images'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  622de389-71f8-4b9f-ba40-260461f3bb7b: # Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      addDefaultOptions: true
      addMobileOptions: false
      defaultWidth: default
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\WidthField
  3580d155-238d-43a1-b359-9c0634e988ed: # Number of Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: numberOfColumns
    instructions: 'Display = Default only'
    name: 'Number of Columns'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4'
            -
              - value
              - '4'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '5'
            -
              - value
              - '5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '6'
            -
              - value
              - '6'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  8625d595-25d0-480e-88cd-cb7c5e9651bd: # Aspect Ratio
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: 'Display = Default only'
    name: 'Aspect Ratio'
    searchable: false
    settings:
      defaultAspectRatio: '1:1'
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\AspectRatioField
  d9da022d-74c8-40d1-bd79-f3a6f208e542: # Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: null
    name: Style
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Carousel
            -
              - value
              - carousel
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - fullWidth
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: gallery
name: Gallery
sortOrder: 4
