field: 7384bc4c-31c8-4906-a830-d53525e01989 # Guide Inhalt
fieldLayouts:
  73609308-c7b9-40fc-a459-200fb062e41f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a5f3b232-51a5-4cf6-88f2-2e1ff35fabb7 # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51bf4f0b-5b07-48e9-b92b-f9e9309439f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea2cfe15-67c5-438e-9d8c-b80a905baa85 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d41cb9d3-1f01-48d4-9cd9-ee71f3e1afb8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17bdd0b8-d122-4c81-accf-6e1470359fba # Bilder
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03d0c64b-573f-451f-835b-bdfc6fbe0842
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 752d79f6-0f1d-438e-91a2-f8e4cedfd23d # Ausrichtung
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3351c80-e322-44c4-b5b1-7d707ac903ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee360814-e45a-409a-b0df-5384fb768d19 # Bildbreite
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b9bb63d-e53d-44d5-ba0e-5d931bd5b040
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e43005be-5177-4738-b739-e3bdaf079733
        userCondition: null
fields:
  17bdd0b8-d122-4c81-accf-6e1470359fba: # Bilder
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Bilder
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionLabel: 'Bild hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:a010299b-071c-4852-81f6-c15875a5ba4f' # Guide
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  752d79f6-0f1d-438e-91a2-f8e4cedfd23d: # Ausrichtung
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: orientation
    instructions: null
    name: Ausrichtung
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Text <-> Bild'
            -
              - value
              - right
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Bild <-> Text'
            -
              - value
              - left
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a5f3b232-51a5-4cf6-88f2-2e1ff35fabb7: # Überschrift
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Überschrift
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ea2cfe15-67c5-438e-9d8c-b80a905baa85: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ee360814-e45a-409a-b0df-5384fb768d19: # Bildbreite
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imgWidth
    instructions: null
    name: Bildbreite
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Breit
            -
              - value
              - wide
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Schmal
            -
              - value
              - small
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: grid
name: Grid
sortOrder: 4
