field: 7384bc4c-31c8-4906-a830-d53525e01989 # Guide Inhalt
fieldLayouts:
  53c3d92e-7376-492e-9e12-8b048de6b637:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3cb2606a-5d91-44a2-bbfa-8110801db82d # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 225a84e2-8b69-420f-bd10-54e6ad8a9642
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb3d5f40-e3f5-45a4-9c9f-47b9c515be67 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d53218d-d61a-4a2b-9c6c-1f8d853103c9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fa0ed66-6eef-4af8-ac30-fdff17e06a07
        userCondition: null
fields:
  3cb2606a-5d91-44a2-bbfa-8110801db82d: # Text
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: 100
      code: false
      columnType: string
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cb3d5f40-e3f5-45a4-9c9f-47b9c515be67: # Tag
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: null
    name: Tag
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: heading
name: Überschrift
sortOrder: 1
