field: 20f9b230-8862-4058-9cf3-7c7a78e44a13 # Column
fieldLayouts:
  d340f488-b27f-4e92-b9e8-f97103648c50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 39a9436c-4a59-44ea-9c7c-5d1a4eef3609 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 096a2554-76da-4e46-a96d-f1740f075889
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 32f77f20-afaa-4208-b9c5-ee0a7cbd6947 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd003a1a-de80-4836-bb09-b06c4a14b3a1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9e2aef67-e059-40ff-8b1a-06707a443c2d # Aspect Ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1299c031-9542-4be3-915e-b29479b11919
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: db5c0b3a-9c87-4c0a-9ed0-bce6a6923d44
        userCondition: null
fields:
  9e2aef67-e059-40ff-8b1a-06707a443c2d: # Aspect Ratio
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: null
    name: 'Aspect Ratio'
    searchable: false
    settings:
      defaultAspectRatio: '16:9'
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\AspectRatioField
  32f77f20-afaa-4208-b9c5-ee0a7cbd6947: # Caption
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: 255
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  39a9436c-4a59-44ea-9c7c-5d1a4eef3609: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 3
