field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  97b01980-d2f7-444c-b77e-7d4c19ea6413:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 499db390-ca29-450f-8c5d-9a23d0e1e353 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70fc2c7d-8dc6-41a4-b74c-4731d6fc5d8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 29e22732-c4a5-4810-82b8-68182df19ad1
        userCondition: null
fields:
  499db390-ca29-450f-8c5d-9a23d0e1e353: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'You can use markdown and reference tags here'
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: markdown
name: 'Text (Markdown)'
sortOrder: 15
