field: 10d8ae84-a8b6-489d-846d-1a7510cd9829 # Global Seo Fields
fieldLayouts:
  69f8429b-14be-40a0-b9d4-a006da256757:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 61c8dfb5-4ac7-420b-ad8e-5cad0d464a98 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d220c53-2355-423a-a3d1-a03161b2db41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48fde250-325a-44bf-9238-66f0e831a883 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a7b9342-d0c5-48d3-bdf8-4ae38e689e0b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e41c862a-9799-4d30-940e-bd52268b2c74
        userCondition: null
fields:
  48fde250-325a-44bf-9238-66f0e831a883: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      defaultUploadLocationSubpath: seo
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      restrictedLocationSubpath: seo
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  61c8dfb5-4ac7-420b-ad8e-5cad0d464a98: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: settings
name: Settings
sortOrder: 1
