field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  124833b8-db6c-4ee3-b676-4559422910cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cbef4b7f-43de-4ceb-b5d9-ad77705319c9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf05e752-dfea-4ece-95d2-5c15754660a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbf29f4d-79b9-4474-b8ff-d05ff24d450e # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93579a0b-9fa5-44da-a94d-be715ea01241
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47d985cf-4ece-47c4-96be-d9ec9087351d
        userCondition: null
fields:
  cbef4b7f-43de-4ceb-b5d9-ad77705319c9: # Heading
    columnSuffix: null
    contentColumnType: string(240)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  dbf29f4d-79b9-4474-b8ff-d05ff24d450e: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: summary
name: Summary
sortOrder: 11
