field: 20f9b230-8862-4058-9cf3-7c7a78e44a13 # Column
fieldLayouts:
  9b6f641c-2c32-4e5a-b55c-a2d295bc9da4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11167327-b2c6-4db1-b01f-3867093255e8 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c597fe2e-df43-4ed2-87a7-c87243193d5a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b7e2f346-ddd7-44d8-a2dd-d8c9dcf06483
        userCondition: null
fields:
  11167327-b2c6-4db1-b01f-3867093255e8: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
