field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  45867f09-a5a7-447e-b633-2ebaf198607d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b69b9f51-3329-4ff9-903f-f7014de6e7f0 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92b547b6-1e17-4f13-b882-5c886534c715
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3c686401-f8c9-46a2-b773-326609a3a10a
        userCondition: null
fields:
  b69b9f51-3329-4ff9-903f-f7014de6e7f0: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Custom.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
