field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  2396ae75-bd1d-4372-9450-ea76a363f922:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2bec7dc-66f2-4af0-9b96-7f9994b1d2c2 # Video File
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c69ce23-17c6-448c-963b-2a8b260966e0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: bc242225-cdbb-4145-9746-471878a85673 # Poster Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93c5c914-673d-42df-be58-476751537835
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 80de78f1-6d38-4d79-a522-71b6e6aec241 # Show in modal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1abb01e-6a27-41aa-befc-ab648082504b
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 3be1e399-665b-4cac-ac85-47db98093223
        userCondition: null
fields:
  80de78f1-6d38-4d79-a522-71b6e6aec241: # Show in modal
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showInModal
    instructions: null
    name: 'Show in modal'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  b2bec7dc-66f2-4af0-9b96-7f9994b1d2c2: # Video File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoFile
    instructions: null
    name: 'Video File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: video
      localizeRelations: true
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bc242225-cdbb-4145-9746-471878a85673: # Poster Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: posterImage
    instructions: null
    name: 'Poster Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Select image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:270fd626-b08d-4f72-9383-3acdcd200225' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: Video
sortOrder: 9
