fieldLayouts:
  1937a214-1ec4-4b42-be75-86046b57e746:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7e805561-f15c-4b30-aaf5-b647ca341e91
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: modules\main\conditions\IsCoverTitleStyleConditionRule
                  uid: bf2d9b73-f26a-4bba-b4ad-d7c103ddfebc
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f8d4230-04ec-4dfc-9fdf-8ed218121fa5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce64d9aa-4d15-43c8-83ee-fd0878857be0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1617cb5d-5789-41ea-8228-2776eb88ca42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a76b8be-7378-48a1-a28c-fd020c2e6af7
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: ed5d37bf-b1cf-499a-8845-c725870822e6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # Seo Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d72cbb60-2a21-4af4-981b-8b3fec194b41
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 584a69ab-78cf-4758-91c1-b4a70901f8c8
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: a3a00a5e-73ba-4e8a-9800-375c9be802a9 # Topic
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
