fieldLayouts:
  5c6605e5-a89b-42c2-9f30-38f97bb5854a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 38f6e713-4137-4c64-88f4-2000701abaa1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e64a3324-79da-4987-b10d-08126fedca89 # First Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b248025e-d064-4e66-ae99-36181685ea6a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f4f2b6fc-3280-4a7f-9b66-5e79d3d86cee # Name Prefix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55862636-3683-44df-8386-a49af8881d5d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ab267fdb-cdb7-4562-b137-c8bba765fe57 # Last Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b01bc44-549f-4530-afb0-a0000ce0bc2e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: modules\main\conditions\IsCoverTitleStyleConditionRule
                  uid: 17dced54-3b04-4316-a1db-107cc6d7e3ee
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a62dad69-efa2-4692-a910-6644a1741aeb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: c4ede7fe-f873-4466-8bbc-73ee9e0c54fa # User
            instructions: 'Assign the user whose entries will be shown'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 081f14a1-62fc-49eb-b744-6dd3e080b9eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5e963153-38ea-4cd9-9282-6d08335433ff # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c4660f1-f3e2-49ef-81a9-d43aa1bae15d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74c8ac40-8073-4058-a003-9f55963ad0ff
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bafbd664-0b38-44ce-93b6-d271eabc05a8 # Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa4e0f9f-1887-425e-b6fe-ade75accf4a1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe53ce0-c7de-47a6-8d29-e21bd015d82c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7a27d1b6-f8c9-4b63-947e-cc535c5082c8 # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e95b054-b0b0-4546-aeb7-2373c6e317f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b356fa75-2cf9-4c16-a4e3-fa453dc9fa40
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 5c2b3f2f-ce91-4a73-af90-b7340abd20ba
        userCondition: null
handle: default
hasTitleField: false
name: Standard
section: d798b89b-cb00-4853-ac5a-c69bffe3ca76 # Person
sortOrder: 1
titleFormat: '{firstName}{{object.namePrefix ? " #{object.namePrefix}" }} {lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
