fieldLayouts:
  e205c5b7-f987-4a6e-baa7-cba8718ee35a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 59eae39d-156e-4c6e-999f-ef1fa51b6cdb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 522d49e6-b053-48d0-aca2-3c370742edb9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cce5096c-8ab7-4940-9973-ad47671c92cb # Admin Guide
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b46fb4ad-c79c-42a7-a48b-95f36a8d45d5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7bb0cd75-a933-4105-b72c-a34605721327 # Auf der Übersichtsseite anzeigen?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73a492e0-e107-4100-ad94-a5e02f00f78a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7384bc4c-31c8-4906-a830-d53525e01989 # Guide Inhalt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90b43144-79a1-4571-9e2a-4c6a3b38357f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e1a9aaa-8ad3-47d5-917c-0c5b2552c7ad # Include Guides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dcecaf0-7802-4fe9-a9e4-c927b807ed5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0088f10c-51c9-4b2a-aa9b-88139c031740
        userCondition: null
handle: guide
hasTitleField: true
name: Guide
section: 61350169-3950-4815-aea9-b171958d6d8a # Guide
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
