fieldLayouts:
  a949fea3-f4a0-45a3-aa39-02573d17cef4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 472b5f83-38dd-42bc-9d1d-bcb41030f7b1
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: modules\main\conditions\IsCoverTitleStyleConditionRule
                  uid: fa27c1e7-7159-42c0-8593-39319046b489
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f48539bc-2546-4525-8c76-2d761775ac38
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7e26cdb-2dbe-4911-ac75-75b20f6e5dc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a2ff105-c064-4748-b9ce-cf2632f0e288
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff691cf2-d76d-4e4c-8921-8cb7da360e4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c301f202-52bb-477a-b6b7-2b4ee598bf4c # Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d6a917b-576d-4a99-8af2-7067a660c327
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aa0f84e8-acb3-403e-a095-1d6f3d9f98bf # Order By
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa37c85f-0042-40d6-b6a2-931e9bc74a25
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3f22fd1a-1b63-4a34-ab28-56dd59bd3e99 # Index Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf7be767-e6cb-4e5f-a2e9-d90df7010732
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d9637c0b-358e-4727-8210-8648a7f0db61 # Criteria
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83511402-0b09-4d18-8853-2e6262ac5a4c
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 68efeb64-bf19-42a2-9485-87b5ef694a6b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # Seo Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf743b51-6046-4c6b-a8de-a976bd9be77a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b82dd02b-fdfb-4181-910f-91de77fab1fd
        userCondition: null
handle: indexPage
hasTitleField: true
name: 'Index Page'
section: a6676538-ee52-4938-aaff-8d9d46b669af # Page
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
