fieldLayouts:
  015c17ec-fb1f-41eb-b395-7ae9226d410d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 41d819ec-24b3-4ab2-85da-66c3b5e17fe9
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: modules\main\conditions\IsCoverTitleStyleConditionRule
                  uid: f84d3293-4a77-460a-a7d5-e3a35d5cf28b
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d346ef7e-5600-4a6a-b45d-88ba426a8cdb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f94e53b-e6a2-4bd7-8b3c-ab410c8701af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 749e5fc7-8ab6-4d4e-8335-1940bf25a0b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4d8c6d2-05ed-4425-b56f-eb5235f46ee9
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 5408b860-4119-45b3-a1ac-43ddac2130a7
        userCondition: null
handle: message
hasTitleField: true
name: Message
section: f839af84-5d1a-4830-9993-f126c2fe2e41 # Message
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
