fieldLayouts:
  c3b8c612-fbc4-487d-b0ad-82b0776afd0e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _cp/help.twig
            type: craft\fieldlayoutelements\Template
            uid: 6e1d512e-3db0-4093-a9b0-adaa6d2e1292
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8b43d267-9138-48a1-9ceb-542b465e7506
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: modules\main\conditions\IsCoverTitleStyleConditionRule
                  uid: 229e6d03-9374-45b8-83c5-53eecc6a27c8
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1eecdd2c-f9c5-4379-b304-d81774f9391e # Increase Title Contrast
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 320d8469-6d3f-40d2-8245-ac675f47a6da
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 101c5c26-6943-441a-be60-b487365bfb78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c11bd967-dddf-4908-9754-39f1f8e51f31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c9d5cca-e9b2-48e2-911d-21f139d26fed # Intro
            instructions: 'Used in Article block, e.g. for the home page'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8fe6fbb-6788-4ce9-b10c-7fc32cbd5487
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfc9ce8f-c136-4e15-829c-72e9317df10b
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: f1d7cf42-3103-42bd-b3fb-ccdd8ce22b53
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # Seo Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 470c2445-f657-4d3f-91e9-7b4a3eeeb715
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9f343fff-1efc-4a71-8018-ebbd7e25a5c2
        userCondition: null
handle: page
hasTitleField: true
name: Page
section: a6676538-ee52-4938-aaff-8d9d46b669af # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
