fieldLayouts:
  c43cd6ab-60e9-49e5-abd5-f80a324860be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97927e3f-816c-485c-9dab-7c5c4bb0e2f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            style: tip
            tip: 'This page type has no content of its own, only the child pages are shown.'
            type: craft\fieldlayoutelements\Tip
            uid: 69e75a3c-1076-403e-8695-0fd809327291
            userCondition: null
        name: Inhalt
        uid: 9b34a6fb-7984-49f2-8acf-46344a403d1e
        userCondition: null
handle: toc
hasTitleField: true
name: 'Table of Content'
section: a6676538-ee52-4938-aaff-8d9d46b669af # Page
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
