fieldLayouts:
  9b1c7447-0610-4464-a01c-e7e4062e9871:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c7d792cf-79ce-463d-a737-c022b7b6bebc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 044f0979-e2b3-4144-895a-f19058d9687d
        userCondition: null
fs: guide
handle: guide
name: Guide
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: transforms
transformSubpath: guide
