fieldLayouts:
  61c69569-f76c-4628-bd88-7392fd3943ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 94a3b13f-3bef-4a96-85e9-37815cbd36a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 27d258a2-a6f5-44f8-9692-e0a1b254cea4 # Alt Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a23d0642-d050-4924-b715-5abff27f8baf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc298055-236a-4bbc-9246-ae94c0e76889 # Copyright
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f31c8d5-7c37-4930-a569-c71426eca1ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0492cf04-a657-4145-a124-7c2f3d500c63 # Copyright Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 332b4d5c-86c4-43d7-adda-e6031e999a05
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: cd6b633e-36fe-4298-a7ea-73617a80f6f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c9b2ed9-86a5-4843-858a-16760e0e5437 # Image Effects
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 176968df-ff32-455a-8dbc-c923457212c6
            userCondition: null
            warning: null
            width: 100
        name: 'Image effects'
        uid: c6cad938-8a3b-4efb-adf6-3fcb96eb901d
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: transforms
transformSubpath: images
