columnSuffix: kymjijsy
contentColumnType: text
fieldGroup: f15bff68-e0e6-422d-a615-9e22d733e1f0 # Global
handle: cookieConsentInfo
instructions: null
name: 'Cookie Consent Info'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
