columnSuffix: drrgftqc
contentColumnType: text
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: criteria
instructions: "Criteria for entry query in json format, e.g.   \r\n{\"section\":\"post\", \"orderBy\":\"title\", \"limit\":10}\r\n\r\nWill take precedence over section/orderBy if specified."
name: Criteria
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: '{"section":"person", "orderBy":"title", "limit":10}'
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
