columnSuffix: null
contentColumnType: string
fieldGroup: b61bea97-e4d4-4de2-9149-15f74906945a # SEO
handle: globalseofields
instructions: null
name: 'Global Seo Fields'
searchable: true
settings:
  contentTable: '{{%matrixcontent_globalseofields}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
