columnSuffix: nmcfhzkm
contentColumnType: string
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: indexSection
instructions: null
name: Section
searchable: false
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\SectionsField
