columnSuffix: wzwfpyvm
contentColumnType: string
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: membersTemplate
instructions: null
name: 'Members Template'
searchable: false
settings:
  includeDirectory: _members
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\IncludeField
