columnSuffix: null
contentColumnType: string
fieldGroup: b61bea97-e4d4-4de2-9149-15f74906945a # SEO
handle: seoFields
instructions: null
name: 'Seo Fields'
searchable: true
settings:
  contentTable: '{{%matrixcontent_seofields}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
