fieldLayouts:
  3ab90f34-a4a8-41a1-8123-3fd957982997:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c191286d-fa58-48a4-bba2-92c28cbf57c9 # Site Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d28835e-e96b-4259-85cc-a22416b8cc85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55c8d23d-ad74-43a2-a3f2-8c4b6d969fe2 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b57fff02-8f9c-4fc9-bf89-6cea95dfefd4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: cc39676d-193e-4b20-a29d-f1b3d3c3c299 # Fav Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a008ae4f-6653-45c0-854c-609dba453669
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6253c3ac-a08c-48bf-986f-d4350ed611d7 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ef4c97a-b789-4401-8cd3-50225938360e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 60a84778-fbac-4fcb-9adc-67569899fb55 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5162f60-092c-49f2-b4fe-d0887135b67d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: dc298055-236a-4bbc-9246-ae94c0e76889 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5b38611-58a0-433b-82fc-bf6eddecd7bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07e4260f-cc8c-4e3c-8085-fa9c9077ddcb # Entries
            instructions: null
            label: 'Navigation Entries'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: babff0cb-ef85-44b7-85fe-70ce5557b8b6
            userCondition: null
            warning: null
            width: 100
        name: Global
        uid: 01adaf9c-18c9-4b9f-a509-8feb1a1ebd41
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94e05a5e-2220-415e-89c6-398c3c22fc07 # Individual contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcdb3fa2-894d-43f8-a2d5-025ef714be16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e963153-38ea-4cd9-9282-6d08335433ff # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 036b8467-9000-442c-b1d9-c52b536bce8e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b683b318-aee5-4bb2-a3a4-40fc6cf445cc # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 775ab8c6-1ae1-4005-b104-4e382e701f9e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 0c3f6026-fb73-4bb2-a6da-63857c5b8db4 # Fax
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c81f955d-3315-4b49-b003-87b670bb5aac
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9e628a7d-eee4-4815-ba1a-502ca992f9c0 # Web Site
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2d021f9-2361-492a-b02a-12c07a505708
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4ad59136-a89e-41ea-8aff-d5383b3a11e0 # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcbd1ba5-d35f-496e-bd85-f3762866472e
            userCondition: null
            warning: null
            width: 100
        name: Kontakt
        uid: 1c0d3ab1-785f-42ce-b865-dda6c0a24b0f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
            instructions: "Leave blank to show default footer.\r\n\r\nDo not change colors here."
            label: 'Footer Content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71ad5388-cf79-41f3-90d6-39b4e035fbc7
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Content'
        uid: 1bf2ef18-18eb-468a-9c30-b9724e776c79
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 23765e34-af93-42cb-bbaf-ea8907bc7407 # Cookie Consent Text
            instructions: 'Dieser Text wird in der Consent-Box neben den Buttons angezeigt'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2961e6d2-b9f4-40b2-80e6-75d8c1915736
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d56f12c-69da-44d0-a0d1-36e975f34020 # Cookie Consent Info
            instructions: 'Dieser Text wird in der Info-Box der Cookie-Consent-Einstellungen angezeigt.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6701d919-3ccb-4d22-a574-8bce7e872630
            userCondition: null
            warning: null
            width: 100
        name: Privacy
        uid: d1e09f7c-8e79-4ae7-b925-75ece0b2c472
        userCondition: null
handle: siteInfo
name: 'Site Info'
sortOrder: 1
