defaultPlacement: end
enableVersioning: false
handle: legal
name: Legal
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6cae2408-4e31-46df-8a5b-33f31d339176: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/legal
    uriFormat: '{slug}'
  b0f125c5-eef7-49fc-8d15-152965d0bab6: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/legal
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: b0dcea43-f2b4-42b3-9406-d846a7e08a31
type: structure
